BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "solo"
BBFILE_PATTERN_solo := "^${LAYERDIR}/"
BBFILE_PRIORITY_solo = "8"

# Depend on NXP BSP release layer + OpenSolo layer stack.
# Use layer collection names (see BBFILE_COLLECTIONS in those layers).
LAYERDEPENDS_solo = "fsl-bsp-release 3dr"

# Declare compatibility with the Yocto scarthgap series.
LAYERSERIES_COMPAT_solo = "scarthgap"
